default['ptc-rails']['db']['adapter'] = 'mysql'
default['ptc-rails']['db']['host'] = '127.0.0.1'
default['ptc-rails']['db']['database'] = 'ptc-db'
default['ptc-rails']['db']['username'] = 'ptc-db'
default['ptc-rails']['db']['password'] = 'changeme'
