default['thunr-rails']['db']['adapter'] = 'mysql'
default['thunr-rails']['db']['host'] = '127.0.0.1'
default['thunr-rails']['db']['database'] = 'thunr-db'
default['thunr-rails']['db']['username'] = 'thunr-db'
default['thunr-rails']['db']['password'] = 'changeme'
